### ISSUE TITLE
Pentagon 512/1024 display garbage

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#68] opened 2016-05-25 14:56 UTC
Me to the rescue, again.

![screenshot_2016-05-25-15-53-35](https://cloud.githubusercontent.com/assets/12862298/15544600/357bc34a-2291-11e6-884d-d313c908c2f3.png)

**Comment by bog-dan-ro** [comment] 2016-05-25 15:05
Any chance to reproduce it?

**Comment by ghost** [comment] 2016-05-25 15:13
I just changed the machine type to Pentagon 512K or Pentagon 1024K and it displayed the screen above.

**Comment by ghost** [comment] 2016-05-25 15:16
Also in the machine type list, if I change from Pentagon 1024K to Pentagon 512K it displays the grey 48k screen.

**Comment by bog-dan-ro** [comment] 2016-05-25 15:20
I just did the same thing and it works ok, probably it depends on what you did before that ...
Did you load any particular game, then tried to switch to pentagon ?

**Comment by ghost** [comment] 2016-05-25 15:26
Whatever it was it now permanently displays that screen when switching to Pentagon 512/1024, even if I exit and reload.

This maybe what did it, set the machine to Spectrum 128K and load an SCL file, does this trigger it on your's ?

**Comment by bog-dan-ro** [comment] 2016-05-25 15:36
Can you try to load another .scl file?

**Comment by ghost** [comment] 2016-05-25 15:47
I can still load SCL files (painfully slow because you still have to manually type RUN "filename"). I just get that weird screen when changing the machine type to Pentagon 512/1024.

**Comment by ghost** [comment] 2016-05-25 17:25
I uninstalled and re-installed and found out that its related to https://github.com/bog-dan-ro/spectacol/issues/63 . If you make the keys repeat bug then it makes the Pentagon 512/1024 model display the screen above.

You say you have fixed https://github.com/bog-dan-ro/spectacol/issues/63 in the upcoming version so this is probably why you couldn't reproduce it. Hopefully its fixed.

**Comment by ghost** [comment] 2016-06-01 09:51
Any release date for a new beta ? That keyboard repeating bug is annoying especially when typing fast with the gamepad it easily happens, then I have to uninstall/reinstall if I want to use the quickboot workaround method on Pentagon. There are build instructions for Windows on the Fuse page so I guess 1.2 is ready ? Maybe not.

**Comment by ghost** [comment] 2016-06-02 18:41
Have you been told by the Fuse team an approximate release date for 1.2 ? The 'nice to have for Fuse 1.2 list is quite long https://sourceforge.net/p/fuse-emulator/wiki/Fuse%201.2%20Release%20Plan/ Is there any reason why you're not releasing any more betas ? Its been over two weeks since the last beta and no new commits have been added for nearly 2 weeks (not even the zip support that you chose instead of the alternate file list view).

**Comment by bog-dan-ro** [comment] 2016-06-02 18:50
They've found a few bugs (this is also the reason why I didn't released any beta)  and it will be delayed a little bit. Regarding the commits, I was quite busy these days and I didn't had any time for Spectacol :(.
If FUSE team will release 1.2 before I'll finish these two pending features, then I'll postpone them for 3.0.

**Comment by ghost** [comment] 2016-06-02 18:56
O.K.

**Comment by ghost** [comment] 2016-06-06 13:31
FUSE-1.2.0-pre1 tarballs have been generated, is this what you'll be using for the next beta or do we have to wait even longer (months ?) before a new BETA is released without the above bugs ? Note that I said BETA. Most of the new features of Fuse aren't even in Spectacol anyway ?

**Comment by bog-dan-ro** [comment] 2016-06-06 14:50
I need to wait for two things before I ship the BETA:
- FUSE 1.2.0 final release and the merge back to trunk branch (I have a few fixes there)
- Qt 5.7.0 which should be released in the next days/weeks

**Comment by ghost** [comment] 2016-06-06 15:58
I'll stick with Spectaculator then, i'll uninstall and check back in a few weeks. I think I was the only person that noticed the bugs anyway.

**Comment by bog-dan-ro** [comment] 2016-06-06 18:22
Fixed by #63

**Comment by bog-dan-ro** [comment] 2016-06-06 18:24
Though, FUSE devs should check why the error happens when key gets repeated

**Comment by ghost** [comment] 2016-06-15 22:21
I'll close this for now, it doesn't seem to happen anymore since you fixed the key repeating bug with the on-screen keyboard.

**Comment by ghost** [comment] 2016-06-17 22:33
This garbage screen on Pentagon has come back but I can't reproduce it like before. Its happened twice now. I'll keep trying to reproduce.

**Comment by bog-dan-ro** [comment] 2016-06-18 06:20
It is the same as #81 ? If yes, then one is enough :)

**Comment by ghost** [comment] 2016-06-18 09:12
No it's not the same as https://github.com/bog-dan-ro/spectacol/issues/81 . It displays the screen I posted at the top of this page on Pentagon 512/1024 but I am having trouble reproducing it this time. It has happened to me twice.

Is this caused by what you just fixed ? https://github.com/bog-dan-ro/spectacol/commit/e1155e08f09160d83d03ef874ce6a8a3df36ec6b

EDIT: Yes, just reproduced it on v2.0.1. If you press fire and close the keyboard at roughly the same time then all hell breaks loose with Pentagon !

**Comment by ghost** [comment] 2016-06-18 09:42
Fixed on v2.0.2.

**Comment by ghost** [comment] 2016-06-18 16:51
Lol, nope still does it !

**Comment by ghost** [comment] 2016-06-18 17:14
To reproduce, 
Press the button to show the on-screen keyboard
Press the button to show the on-screen joystick
Press Start to open the side menu, it will immediately close
Remove the on-screen keyboard/joystick and change machine type to Pentagon 512/1024. You will see the picture at the top of this page, and if you change to a system that doesn't start with a menu you will see the cursor continuously flashing like a key is being held down.

I think there are also other ways that this happens but I found this way to always reproduce it.

**Closed as completed** 2016-06-19 07:03 UTC
Labels: bug, upstreamed
