### ISSUE TITLE
Screen tearing on some games

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#49] opened 2016-04-24 14:22 UTC
As the title says, this on top of the bad scaling makes your eyes hurt. Also, anything that scrolls looks a jumpy mess.

**Comment by bog-dan-ro** [comment] 2016-04-24 16:10
Are you using any screen filters?
Anyway I implemented the fixed scaling #16 yesterday.

**Comment by ghost** [comment] 2016-04-24 16:23
No, my filter says Normal but it looks the same as before, as was reported here -

http://www.worldofspectrum.org/forums/discussion/comment/854597/#Comment_854597

"You can see that the fonts look weird - some thick lines, so thin lines. I believe this is because my screen res isn't an exact multiple of Speccy resolution, so some rows/columns of pixels are doubled up while others aren't."

Is this the reason for screen tearing and very jerky scrolling ?

**Comment by bog-dan-ro** [comment] 2016-04-24 16:43
It should not, the resizing is don on the GPU side and it should be pretty fast.

Duplicate of #16

I'll try to publish the first alpha of v 2.0 soon

**Closed as completed by bog-dan-ro** 2016-04-24 16:43 UTC
Labels: duplicate
